---
- when: podman is defined
  block:
    - name: "Install required packages"
      ansible.builtin.import_role:
        name: "{{ __packages_role__ }}"
      vars:
        packages_present: "{{ packages_present_podman }}"
        call_from: podman role
      tags: install

    - name: "Configure podman networks"
      when: network | d(podnet.name) == podnet.name
      ansible.builtin.include_tasks: network.yml
      loop: "{{ podman.networks | d([]) }}"
      loop_control:
        loop_var: podnet
        label: "{{ podnet.name }}"
      tags: network

    - name: "Configure pods"
      when: podname | d(pod[0]) == pod[0]
      ansible.builtin.include_tasks: pod.yml
      loop: "{{ (podman.pods | d({})).items() }}"
      loop_control:
        loop_var: pod
        label: "{{ pod[0] }}"
      tags:
        - pod
        - pull

    - name: "Configure podman containers"
      when: podcont | d(containter[0]) == container[0]
      ansible.builtin.include_tasks: container.yml
      loop: "{{ (podman.containers | d({})).items() }}"
      loop_control:
        loop_var: container
        label: "{{ container[0] }}"
      tags:
        - container
        - pull
