---
# code: language=ansible
- name: "Execute podman tasks when podman is defined"
  when: podman is defined
  block:
    - name: "Install podman"
      ansible.builtin.import_tasks: install.yml
      tags: install

    - name: "Configure podman"
      ansible.builtin.import_tasks: config.yml
      tags:
        - config
        - configure

    - name: "Configure podman networks"
      when: network | d(podnet.name) == podnet.name
      ansible.builtin.include_tasks: network.yml
      loop: "{{ podman.networks | d([]) }}"
      loop_control:
        loop_var: podnet
        label: "{{ podnet.name }}"
      tags: network

    - name: "Configure pods"
      when: podname | d(pname) == pname
      ansible.builtin.include_tasks: pod.yml
      loop: "{{ podman.pods | d([]) }}"
      loop_control:
        loop_var: pname
        label: "{{ pname }}"
      tags:
        - pod
        - pull

    - name: "Configure podman containers"
      when: podcont | d(container[0]) == container[0]
      ansible.builtin.include_tasks: container.yml
      loop: "{{ (podman.containers | d({})).items() }}"
      loop_control:
        loop_var: container
        label: "{{ container[0] }}"
      tags:
        - container
        - pull

    - name: "Configure /etc/profile.d/podman.sh"
      ansible.builtin.import_tasks: profile.yml
      tags:
        - profile

    - name: "Configure Monitoring"
      ansible.builtin.import_tasks: checkmk.yml
      tags:
        - never
        - checkmk
        - cmk
        - monitoring
