---
# code: language=ansible
- name: "Execute podman tasks when podman is defined"
  when: podman is defined
  block:
    - name: "Install required packages"
      ansible.builtin.import_role:
        name: "{{ __fqcn_packages__ }}"
      vars:
        packages_present: "{{ packages_present_podman }}"
        call_from: podman role
      tags: install

    - name: "Configure podman networks"
      when: network | d(podnet.name) == podnet.name
      ansible.builtin.include_tasks: network.yml
      loop: "{{ podman.networks | d([]) }}"
      loop_control:
        loop_var: podnet
        label: "{{ podnet.name }}"
      tags: network

#    - name: "Verify that pause image is available"
#      become: true
#      containers.podman.podman_image:
#        name: "podman-pause"
#        pull: true

    - name: "Configure pods"
      when: podname | d(pname) == pname
      ansible.builtin.include_tasks: pod.yml
      loop: "{{ podman.pods | d([]) }}"
      loop_control:
        loop_var: pname
        label: "{{ pname }}"
      tags:
        - pod
        - pull

    - name: "Configure podman containers"
      when: podcont | d(container[0]) == container[0]
      ansible.builtin.include_tasks: container.yml
      loop: "{{ (podman.containers | d({})).items() }}"
      loop_control:
        loop_var: container
        label: "{{ container[0] }}"
      tags:
        - container
        - pull
