---
# code: language=ansible
- name: "Configure podman network instance"
  become: true
  tags: network
  block:
    - name: "Configure podman network {{ podnet.name }}"
      containers.podman.podman_network:
        debug: "{{ podnet.debug | d(omit) }}"
        disable_dns: "{{ podnet.disable_dns | d(omit) }}"
        driver: "{{ podnet.driver | d(omit) }}"
        executable: "{{ podnet.executable | d(omit) }}"
        force: "{{ podnet.force | d(omit) }}"
        gateway: "{{ podnet.gateway | d(omit) }}"
        internal: "{{ podnet.internal | d(omit) }}"
        ip_range: "{{ podnet.ip_range | d(omit) }}"
        ipv6: "{{ podnet.ipv6 | d(omit) }}"
        name: "{{ podnet.name }}"
        opt: "{{ podnet.opt | d(omit) }}"
        recreate: "{{ podnet.recreate | d(omit) }}"
        state: "{{ podnet.state | d(omit) }}"
        subnet: "{{ podnet.subnet | d(omit) }}"
      register: out

#    - debug:
#        var: out
