---
- block:
    - name: "Configure podman network {{ podnet[0] }}"
      containers.podman.podman_network:
        debug: "{{ podnet[1].debug | d(omit) }}"
        disable_dns: "{{ podnet[1].disable_dns | d(omit) }}"
        driver: "{{ podnet[1].driver | d(omit) }}"
        executable: "{{ podnet[1].executable | d(omit) }}"
        force: "{{ podnet[1].force | d(omit) }}"
        gateway: "{{ podnet[1].gateway | d(omit) }}"
        internal: "{{ podnet[1].internal | d(omit) }}"
        ip_range: "{{ podnet[1].ip_range | d(omit) }}"
        ipv6: "{{ podnet[1].ipv6 | d(omit) }}"
        # deprecated
        #macvlan: "{{ podnet[1].macvlan | d(omit) }}"
        name: "{{ podnet[0] }}"
        opt: "{{ podnet[1].opt | d(omit) }}"
        recreate: "{{ podnet[1].recreate | d(omit) }}"
        state: "{{ podnet[1].state | d(omit) }}"
        subnet: "{{ podnet[1].subnet | d(omit) }}"
      register: out

#    - debug:
#        var: out
  tags: network
